Repository ultralytics/hub-sdk, pull requests merged in 2024-12, with the labels that each got.

#229 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, devops

#230 Update ci.yml
  .github/workflows/ci.yml
Labels: enhancement, devops

#231 Split PyPI publish jobs for improved security
  .github/workflows/publish.yml
Labels: HUB, enhancement, devops

#232 `hub-sdk 0.0.17` Security improvements
  hub_sdk/__init__.py
Labels: HUB, dependencies, enhancement

#234 Update format.yml
  .github/workflows/format.yml
Labels: enhancement, devops

#235 Update links.yml
  .github/workflows/links.yml
Labels: enhancement, devops

#236 Delete .github/workflows/ci.yml
  .github/workflows/ci.yml
Labels: documentation, devops

#237 Create ci.yml
  .github/workflows/ci.yml
Labels: enhancement, devops

#238 Add Exponential Backoff to Model Export Status Check
  tests/features/model.py
Labels: enhancement, devops, exports
