Repository ultralytics/hub-sdk, pull requests merged in 2024-11, with the labels that each got.

#219 Update environment in publish.yml
  .github/workflows/publish.yml
  hub_sdk/__init__.py
Labels: devops

#220 Fix PyPI downloads links
  README.md
Labels: documentation

#221 Use new Ultralytics Retry action
  .github/workflows/links.yml
Labels: enhancement, devops

#222 Use new Ultralytics Retry action
  .github/workflows/links.yml
  tests/utils/test_data.py
Labels: enhancement, devops

#224 Update to Slack API v2
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  hub_sdk/__init__.py
Labels: enhancement, devops

#226 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/publish.yml
Labels: enhancement

#227 Delete .github/workflows/codeql.yaml
  .github/workflows/codeql.yaml
Labels: devops

#228 Favicon updates
  docs/assets/favicon.png
  docs/assets/logo.svg
  mkdocs.yml
Labels: documentation, enhancement
