Repository ultralytics/hub-sdk, pull requests merged in 2024-08, with the labels that each got.

#174 Update `mkdocs-ultralytics-plugin>=0.1.0`
  pyproject.toml
Labels: dependencies, documentation

#175 Update `mkdocs-ultralytics-plugin>=0.1.2`
  pyproject.toml
Labels: dependencies

#176 Ultralytics Actions JSON, CSS and autolabel support
  .github/workflows/format.yml
Labels: dependencies, enhancement

#178 Update publish.yaml
  .github/workflows/publish.yaml
  hub_sdk/__init__.py
Labels: dependencies, enhancement

#179 Fix repo name in publish.yaml action
  .github/workflows/publish.yaml
Labels: enhancement

#180 Update publish.yml to GPT4o-08-06
  .github/workflows/publish.yaml
Labels: dependencies, enhancement

#182 Update publish.yaml to use gh
  .github/workflows/publish.yaml
Labels: dependencies, enhancement

#186 Ruff Docs reformat
  tests/conftest.py
  tests/functional/test_auth.py
  tests/functional/test_dataset.py
  tests/functional/test_model.py
  tests/functional/test_project.py
Labels: documentation, enhancement

#187 Add https://www.reddit.com/r/Ultralytics/ badge
  README.md
Labels: documentation, enhancement

#188 Update publish.yaml
  .github/workflows/publish.yaml
Labels: dependencies, enhancement

#189 Update publish.yaml
  .github/workflows/publish.yaml
Labels: dependencies, documentation, enhancement

#190 Update to v0.0.10
  hub_sdk/__init__.py
Labels: dependencies, enhancement
