Repository ultralytics/hub-sdk, pull requests merged in 2024-10, with the labels that each got.

#207 Update publish.yaml for trusted publisher
  .github/workflows/publish.yaml
Labels: enhancement

#208 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
  hub_sdk/__init__.py
Labels: documentation, enhancement

#213 Update README.md
  README.md
Labels: documentation, enhancement

#214 Ultralytics Code Refactor https://ultralytics.com/actions
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#215 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#216 Update publish.yml
  .github/workflows/publish.yml
Labels: dependencies, enhancement

#217 Python 3.13 update
  .github/workflows/publish.yml
  pyproject.toml
Labels: dependencies, enhancement

#218 Update publish.yml
  .github/workflows/publish.yml
  hub_sdk/__init__.py
Labels: devops
