Repository ultralytics/hub-sdk, pull requests merged in 2024-09, with the labels that each got.

#191 PyUpgrade 3.8 updates
  tests/test_data/data.py
Labels: dependencies, enhancement

#193 Update `mkdocs-ultralytics-plugin>=0.1.8`
  pyproject.toml
Labels: dependencies, documentation, enhancement

#196 Ultralytics Code Refactor https://ultralytics.com/actions
  README.md
Labels: documentation, enhancement

#197 Update .gitignore
  .gitignore
Labels: enhancement

#199 Delete .github/workflows/greetings.yml
  .github/workflows/greetings.yml
Labels: enhancement

#200 Update publish.yaml
  .github/workflows/publish.yaml
Labels: enhancement

#201 Update pyproject.toml project URLs
  pyproject.toml
Labels: documentation, enhancement

#202 Remove codecov from README
  README.md
Labels: documentation

#203 `hub-sdk 0.0.11`
  hub_sdk/__init__.py
Labels: dependencies, enhancement

#205 Update hub_client.py for single API call
  hub_sdk/__init__.py
  hub_sdk/hub_client.py
Labels: dependencies, enhancement
