Repository ultralytics/hub-sdk, pull requests merged in 2025-01, with the labels that each got.

#239 Ultralytics Refactor https://ultralytics.com/actions
  .github/workflows/format.yml
Labels: enhancement, devops

#240 Apply `ruff==0.9.0` formatting
  hub_sdk/base/auth.py
  tests/functional/test_dataset.py
  tests/functional/test_model.py
  tests/functional/test_project.py
Labels: enhancement, devops

#241 Standardize license headers in Python files
  hub_sdk/__init__.py
  hub_sdk/base/__init__.py
  hub_sdk/base/api_client.py
  hub_sdk/base/auth.py
  hub_sdk/base/crud_client.py
  hub_sdk/base/paginated_list.py
  hub_sdk/base/server_clients.py
  hub_sdk/config.py
  hub_sdk/helpers/__init__.py
  hub_sdk/helpers/error_handler.py
  hub_sdk/helpers/exceptions.py
  hub_sdk/helpers/logger.py
  hub_sdk/helpers/utils.py
  hub_sdk/hub_client.py
  hub_sdk/modules/__init__.py
  hub_sdk/modules/datasets.py
  hub_sdk/modules/models.py
  hub_sdk/modules/projects.py
  hub_sdk/modules/teams.py
  hub_sdk/modules/users.py
  tests/conftest.py
  tests/features/__init__.py
  tests/features/dataset.py
  tests/features/model.py
  tests/features/object_manager.py
  tests/features/project.py
  tests/functional/__init__.py
  tests/functional/test_auth.py
  tests/functional/test_dataset.py
  tests/functional/test_model.py
  tests/functional/test_project.py
  tests/test.py
  tests/testCase_dataset.py
  tests/testCase_model.py
  tests/testCase_project.py
  tests/test_data/__init__.py
  tests/test_data/data.py
  tests/utils/__init__.py
  tests/utils/base_class.py
  tests/utils/test_data.py
Labels: documentation

#242 Improved Python file headers
  hub_sdk/__init__.py
Labels: HUB, dependencies

#243 Standardize license headers in Python files
  hub_sdk/__init__.py
  hub_sdk/base/__init__.py
  hub_sdk/base/api_client.py
  hub_sdk/base/auth.py
  hub_sdk/base/crud_client.py
  hub_sdk/base/paginated_list.py
  hub_sdk/base/server_clients.py
  hub_sdk/config.py
  hub_sdk/helpers/__init__.py
  hub_sdk/helpers/error_handler.py
  hub_sdk/helpers/exceptions.py
  hub_sdk/helpers/logger.py
  hub_sdk/helpers/utils.py
  hub_sdk/hub_client.py
  hub_sdk/modules/__init__.py
  hub_sdk/modules/datasets.py
  hub_sdk/modules/models.py
  hub_sdk/modules/projects.py
  hub_sdk/modules/teams.py
  hub_sdk/modules/users.py
  tests/conftest.py
  tests/features/__init__.py
  tests/features/dataset.py
  tests/features/model.py
  tests/features/object_manager.py
  tests/features/project.py
  tests/functional/__init__.py
  tests/functional/test_auth.py
  tests/functional/test_dataset.py
  tests/functional/test_model.py
  tests/functional/test_project.py
  tests/test.py
  tests/testCase_dataset.py
  tests/testCase_model.py
  tests/testCase_project.py
  tests/test_data/__init__.py
  tests/test_data/data.py
  tests/utils/__init__.py
  tests/utils/base_class.py
  tests/utils/test_data.py
Labels: documentation

#244 Standardize license headers in TOML/YAML files
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/cla.yml
  .github/workflows/format.yml
  .github/workflows/links.yml
  .github/workflows/publish.yml
  .github/workflows/stale.yml
  .pre-commit-config.yaml
  mkdocs.yml
  pyproject.toml
Labels: documentation

#246 Update pyproject.toml
  pyproject.toml
Labels: devops

#247 mkdocs-ultralytics-plugin>=0.1.16
  pyproject.toml
Labels: dependencies, documentation

#248 Update links.yml
  .github/workflows/links.yml
Labels: documentation, devops
