Repository ultralytics/hub-sdk, pull requests merged in 2025-03, with the labels that each got.

#250 Update `threaded()` to conform to `ultralytics` implementation
  hub_sdk/__init__.py
  hub_sdk/helpers/utils.py
Labels: enhancement, devops

#251 Fix Example: -> Examples:
  hub_sdk/helpers/utils.py
Labels: documentation

#252 Ultralytics Refactor https://ultralytics.com/actions
  README.md
Labels: HUB, documentation

#253 Update README.md
  README.md
Labels: documentation
