Repository ultralytics/hub-sdk, pull requests merged in 2025-08, with the labels that each got.

#266 docs: 📝 add missing import statement for HUBClient in README.md
  README.md
Labels: HUB, documentation

#268 Anchore SBOM CI fixes
  .github/workflows/publish.yml
  hub_sdk/__init__.py
Labels: devops

#269 Fix SBOM uv ops
  .github/workflows/publish.yml
  hub_sdk/__init__.py
Labels: devops

#272 Ultralytics Refactor https://ultralytics.com/actions
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/workflows/links.yml
  README.md
Labels: documentation, devops
